app:
  jwt:
    secretKey: ${random.value}
  url: http://localhost:8080
  secret: ${random.value}
  user:
    verification: "false"
  email:
    from: sveri80@gmail.com
    support: sveri80@gmail.com
    url: http://localhost:8080
spring:
  thymeleaf:
    mode: HTML5
    cache: "false"
  datasource:
    url: jdbc:h2:file:~/spring-starter
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: create
  mail:
    host: localhost
    default-encoding: UTF-8
  logging:
    file: default.log
    level:
      org:
        springframework:
          jdbc: DEBUG
