logging:
  file: historify.log

app:
  user:
    verification: "false"
    root: users/
spring:
  thymeleaf:
    mode: HTML5
  mail:
    host: localhost
    default-encoding: UTF-8

---
  
app:
  jwt:
    secretKey: glcngfnxvlmbcb3m45rtnbfia990hbuiansernuzipmbzufgns
  url: http://localhost:8080
  secret: fljijwernl34lk23j4KWDFLJjknfaskdfjlk34
  user:
    verification: "false"
    root: users/
  email:
    from: sveri80@gmail.com
    support: sveri80@gmail.com
    url: http://localhost:8080
spring:
  profiles: development
  thymeleaf:
    cache: "false"
  datasource:
    url: jdbc:h2:file:~/spring-starter
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
logging:
  file: historify.log
  level:
    org:
      springframework:
        jdbc: DEBUG
        
---

app:
  url: http://localhost:8080
  email:
    from: sveri80@gmail.com
    support: sveri80@gmail.com
    url: http://historify.sveri.de
spring:
  profiles: production
  thymeleaf:
    cache: "true"
  datasource:
    url: jdbc:postgres://postgres/historify
    username: historify
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
logging:
  file: historify.log
  level:
    org:
      springframework:
        jdbc: ERROR
