app:
  jwt:
    secretKey: glcngfnxvlmbcb3m45rtnbfia990hbuiansernuzipmbzufgns
  url: http://localhost:8080
  secret: fljijwernl34lk23j4KWDFLJjknfaskdfjlk34
  user:
    verification: "false"
    root: users/
  email:
    from: sveri80@gmail.com
    support: sveri80@gmail.com
    url: http://localhost:8080
  spring:
    thymeleaf:
      mode: HTML5
      cache: "false"
    datasource:
      url: jdbc:h2:file:~/spring-starter
      username: sa
      password: sa
      driver-class-name: org.h2.Driver
    jpa:
      show-sql: "true"
      hibernate:
        ddl-auto: update
    mail:
      host: localhost
      default-encoding: UTF-8
  logging:
    file: default.log
    level:
      org:
        springframework:
          jdbc: DEBUG
          